FROM python:3.8-slim

WORKDIR /app

COPY requirements-old.txt .
RUN pip install --no-cache-dir -r requirements-old.txt

COPY /app .

EXPOSE 800

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]