name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and push Docker images
        run: docker build -t hakiozdem/container-image-security:1 .
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: hakiozdem/container-image-security:1
          exit-code: '1'
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          
    
